version: "3.8"
services:
  postgres:
    container_name: postgres
    image: postgres:15-alpine3.17
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: classting
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    networks:
      - app-network

  adminer:
    container_name: adminer
    image: adminer:4.8.1
    restart: always
    ports:
      - "8080:8080"
    networks:
      - app-network

  server:
    platform: linux/amd64
    container_name: server
    build:
      dockerfile: server/Dockerfile
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./server/src:/app/src
      - ./server/.env:/app/.env
    networks:
      - app-network
    environment:
      - ENV=dev
    depends_on:
      - postgres

networks:
  app-network:
    driver: bridge